---
title: "INLAMRAvignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{INLAMRAvignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
```

```{r, include=TRUE}
library(MRAinla)
data("MODISdataTraining")
data("MODISdataTest")
fittedModel <- INLAMRA(
  responseVec = MODISdataTraining@data$y,
  covariateFrame = subset(MODISdataTraining@data, select = -y),
  spatialCoordMat = MODISdataTraining@sp@coords,
  timePOSIXctVec = time(MODISdataTraining),
  predCovariateFrame = MODISdataTest@data,
  predSpatialCoordMat = MODISdataTest@sp@coords,
  predTimePOSIXctVec = time(MODISdataTest),
  sinusoidalProjection = FALSE,
  spatialRangeList = NULL, 
  timeRangeList = NULL, 
  FEmuVec = rep(0, ncol(MODISdataTraining@data)),
  control = INLAMRA.control(
    Mlon = 3,
    Mlat = 3,
    Mtime = 1,
    numKnotsRes0 = 20,
    tipKnotsThinningRate = 0.5
  )
)

fittedModel$hyperMarginalMoments
```
