# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setupNestedGrids <- function(responseValues, spCoords, predCoords, obsTime, predTime, covariateMatrix, predCovariateMatrix, Mlon, Mlat, Mtime, lonRange, latRange, timeRange, randomSeed, numKnotsRes0, J, distMethod, MaternParsHyperpars, fixedEffParsHyperpars, errorParsHyperpars, FEmuVec, nuggetSD, normalHyperprior, tipKnotsThinningRate, numOpenMPthreads) {
    .Call('_MRAinla_setupNestedGrids', PACKAGE = 'MRAinla', responseValues, spCoords, predCoords, obsTime, predTime, covariateMatrix, predCovariateMatrix, Mlon, Mlat, Mtime, lonRange, latRange, timeRange, randomSeed, numKnotsRes0, J, distMethod, MaternParsHyperpars, fixedEffParsHyperpars, errorParsHyperpars, FEmuVec, nuggetSD, normalHyperprior, tipKnotsThinningRate, numOpenMPthreads)
}

LogJointHyperMarginalToWrap <- function(treePointer, MaternHyperpars, fixedEffSD, errorSD, recordFullConditional, processPredictions) {
    .Call('_MRAinla_LogJointHyperMarginalToWrap', PACKAGE = 'MRAinla', treePointer, MaternHyperpars, fixedEffSD, errorSD, recordFullConditional, processPredictions)
}

GetFullCondMean <- function(treePointer) {
    .Call('_MRAinla_GetFullCondMean', PACKAGE = 'MRAinla', treePointer)
}

GetFullCondSDs <- function(treePointer) {
    .Call('_MRAinla_GetFullCondSDs', PACKAGE = 'MRAinla', treePointer)
}

ComputeCondPredStats <- function(treePointer) {
    .Call('_MRAinla_ComputeCondPredStats', PACKAGE = 'MRAinla', treePointer)
}

GetNumTips <- function(treePointer) {
    .Call('_MRAinla_GetNumTips', PACKAGE = 'MRAinla', treePointer)
}

GetPredObsOrder <- function(treePointer) {
    .Call('_MRAinla_GetPredObsOrder', PACKAGE = 'MRAinla', treePointer)
}

GetHmat <- function(treePointer) {
    .Call('_MRAinla_GetHmat', PACKAGE = 'MRAinla', treePointer)
}

GetQmat <- function(treePointer) {
    .Call('_MRAinla_GetQmat', PACKAGE = 'MRAinla', treePointer)
}

GetErrorSD <- function(treePointer) {
    .Call('_MRAinla_GetErrorSD', PACKAGE = 'MRAinla', treePointer)
}

