# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setupGridCpp <- function(responseValues, spCoords, obsTime, covariateMatrix, M, lonRange, latRange, timeRange, randomSeed, cutForTimeSplit, splitTime) {
    .Call('_MRAinla_setupGridCpp', PACKAGE = 'MRAinla', responseValues, spCoords, obsTime, covariateMatrix, M, lonRange, latRange, timeRange, randomSeed, cutForTimeSplit, splitTime)
}

LogJointHyperMarginalToWrap <- function(treePointer, MRAhyperparas, fixedEffSD, errorSD, MRAcovParasGammaAlphaBeta, FEmuVec, fixedEffGammaAlphaBeta, errorGammaAlphaBeta, matern, spaceNuggetSD, timeNuggetSD, recordFullConditional, optimFun, LUfun) {
    .Call('_MRAinla_LogJointHyperMarginalToWrap', PACKAGE = 'MRAinla', treePointer, MRAhyperparas, fixedEffSD, errorSD, MRAcovParasGammaAlphaBeta, FEmuVec, fixedEffGammaAlphaBeta, errorGammaAlphaBeta, matern, spaceNuggetSD, timeNuggetSD, recordFullConditional, optimFun, LUfun)
}

GetFullCondMean <- function(treePointer) {
    .Call('_MRAinla_GetFullCondMean', PACKAGE = 'MRAinla', treePointer)
}

GetFullCondSDs <- function(treePointer) {
    .Call('_MRAinla_GetFullCondSDs', PACKAGE = 'MRAinla', treePointer)
}

ComputeCondPredStats <- function(treePointer, spCoordsForPredict, timeForPredict, covariateMatrixForPredict) {
    .Call('_MRAinla_ComputeCondPredStats', PACKAGE = 'MRAinla', treePointer, spCoordsForPredict, timeForPredict, covariateMatrixForPredict)
}

