# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(str) {
    .Call('_MRAinla_start_profiler', PACKAGE = 'MRAinla', str)
}

stop_profiler <- function() {
    .Call('_MRAinla_stop_profiler', PACKAGE = 'MRAinla')
}

setupGridCpp <- function(responseValues, spCoords, obsTime, M, lonRange, latRange, timeRange, randomSeed, cutForTimeSplit, covarianceParameter) {
    .Call('_MRAinla_setupGridCpp', PACKAGE = 'MRAinla', responseValues, spCoords, obsTime, M, lonRange, latRange, timeRange, randomSeed, cutForTimeSplit, covarianceParameter)
}

logLikCpp <- function(treePointer) {
    .Call('_MRAinla_logLikCpp', PACKAGE = 'MRAinla', treePointer)
}

